apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    url: mariadb:3306
    user: avea
    secureJsonData:
      password: devpassword
    jsonData:
      database: asset_vuln_manager
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      tlsAuth: false
      tlsAuthWithCACert: false
    isDefault: true
    editable: true